### ISSUE TITLE
The extension stopped working

### ISSUE THREAD

**Issue by sorregom** [alexkrechik/VSCucumberAutoComplete#149]
This is the message that always appear on the output console of vscode

TypeError: Cannot read property 'populate' of undefined
    at populateHandlers (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:87:34)
    at documents.onDidOpen (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:91:5)
    at CallbackList.invoke (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at connection.onDidOpenTextDocument (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-languageserver/lib/main.js:172:29)
    at handleNotification (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:483:43)
    at processMessageQueue (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:255:17)
    at Immediate.<anonymous> (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
TypeError: Cannot read property 'validate' of undefined
    at text.split.reduce (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:116:56)
    at Array.reduce (native)
    at validate (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:114:33)
    at documents.onDidChangeContent (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:129:25)
    at CallbackList.invoke (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at connection.onDidOpenTextDocument (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-languageserver/lib/main.js:173:38)
    at handleNotification (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:483:43)
    at processMessageQueue (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:255:17)
    at Immediate.<anonymous> (/Users/sorregom/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:242:13)

**Comment by alexkrechik** [comment]
Looks like you have some steps in cucumberautocomplete settings, but there are no stepsHandler entity. Looks like, that there are some combination of extension settings/steps that lead to the some unhandled error. Could you please check them or provide extensions settings for debug?

**Comment by sorregom** [comment]
this is the .vscode/settings.json 
{
  "cucumberautocomplete.steps": [
      "core/step_definitions/**/*.ts"
  ],
  "cucumberautocomplete.syncfeatures": "features/*.feature",
  "editor.quickSuggestions": {
      "comments": false,
      "strings": true,
      "other": true
  }
}

And this is the User settings file:

{
    "editor.tabSize": 2,
    "extensions.ignoreRecommendations": false,
    "workbench.iconTheme": "vscode-icons",
    "editor.renderWhitespace": "all",
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false
}

**Comment by alexkrechik** [comment]
Please try to use "*" for your pathes and reply here with result.
Examples:
"cucumberautocomplete.syncfeatures": "features/*.feature",
core/step_definitions/**/*.ts"

**Comment by sorregom** [comment]
Sorry, problem with the copy paste, it's already with "
I tried rewriting the " again but same result

**Comment by alexkrechik** [comment]
Yeah, 'code' formatting should be used for this. I'll try to reproduce your issue anyway.

**Comment by sorregom** [comment]
sorry about that, thank you

**Comment by sorregom** [comment]
I've tested the problem in windows and Mac, the problem seems to be only on macbook

**Comment by alexkrechik** [comment]
No errors should appear in 2.6.0. But, If extension will not work after some time, some additional debug required.
