### ISSUE TITLE
Pressing F12 or selecting a feature file causes error

### ISSUE THREAD

**Issue by AllanMedeiros** [alexkrechik/VSCucumberAutoComplete#151]
It seems it doesn't work anymore on last stable VS Code1.18.1.
When I hit F12 to try to go to step definition I got this: Request textDocument/definition failed with message: Cannot read property 'getDefinition' of undefined.
And when a feature file is opened, these main errors appear in the output, among other ones: 
Cannot read property 'populate' of undefined 
Cannot read property 'validate' of undefined

Here is my settings file contents:

```
{
    "cucumberautocomplete.steps": [
        "features/step_definitions/*.rb"
        
    ],
    "cucumberautocomplete.syncfeatures": "features/*feature"
}
```

Tried *.feature instead of *feature and didn't make a difference.
Thanks.

**Comment by alexkrechik** [comment]
Is "features/step_definitions/*.rb" path marked with green warning in the vscode settings file ?

**Comment by AllanMedeiros** [comment]
It seems fine.
![captura de tela 2017-12-19 as 08 27 38](https://user-images.githubusercontent.com/34678196/34152769-dcbbff44-e496-11e7-8cd7-9355b212448d.png)

**Comment by AllanMedeiros** [comment]
Wait, I simply edited the file, saved, reverted back to the same as above and saved again, now I see the green warning saying "No steps file found".
Which is really weird as I double checked the path is it's correct. Any idea?
![captura de tela 2017-12-19 as 08 37 54](https://user-images.githubusercontent.com/34678196/34153100-043ecaf0-e498-11e7-8ad0-8911795e645e.png)

**Comment by AllanMedeiros** [comment]
Should I try an absolute path?

**Comment by alexkrechik** [comment]
No, your path should be related to the app root. Is 'features' folder in the root of app ?

**Comment by alexkrechik** [comment]
Also, looks like that your have some error with 'syncFeatures' path

**Comment by AllanMedeiros** [comment]
I doesn't matter if syncFeatures path is wrong, the green warning is never displayed. 
I've already fixed that one, was just forcing a change in the file.
features folder is in the root of app.

**Comment by alexkrechik** [comment]
Extension just creating combination of `workspaceRoot + '/' + each path in settings`. If it found no files for some option - it just push warning to the settings files, so its something wrong with this path anyway.
Unfortunately, there are no such feature for the syncFeatures implemented yet.

**Comment by AllanMedeiros** [comment]
Although the path has the green warning it's correct and the warning was displayed only after changing to a wrong path and saving. Even when reverting the path back to the correct one, the green warning is still displayed, but if I restart VS Code, then it goes away.

**Comment by AllanMedeiros** [comment]
Also, I'm getting these errors in output when any feature file is selected.

```
TypeError: Cannot read property 'populate' of undefined
    at populateHandlers (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:87:34)
    at documents.onDidOpen (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:91:5)
    at CallbackList.invoke (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at connection.onDidOpenTextDocument (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-languageserver/lib/main.js:172:29)
    at handleNotification (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:483:43)
    at processMessageQueue (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:255:17)
    at Immediate.<anonymous> (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
TypeError: Cannot read property 'validate' of undefined
    at text.split.reduce (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:116:56)
    at Array.reduce (native)
    at validate (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:114:33)
    at documents.onDidChangeContent (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/server.js:129:25)
    at CallbackList.invoke (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at connection.onDidOpenTextDocument (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-languageserver/lib/main.js:173:38)
    at handleNotification (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:483:43)
    at processMessageQueue (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:255:17)
    at Immediate.<anonymous> (/Users/alhemed/.vscode/extensions/alexkrechik.cucumberautocomplete-2.5.0/server/node_modules/vscode-jsonrpc/lib/main.js:242:13)

```

**Comment by AllanMedeiros** [comment]
I've deleted VS Code and settings file, installed back again, installed the plugin and got same results...
My OS X is 10.12.6 Sierra.

**Comment by alexkrechik** [comment]
No errors should appear in 2.6.0. But, If extension will not work after some time, some additional debug required.
