### ISSUE TITLE
Cucumberautocomplete -  No steps file found

### ISSUE THREAD

**Issue by tshroza** [alexkrechik/VSCucumberAutoComplete#235]
**Describe the bug**
Hi! I have project, but after trying launch it on new PC with installed programs I get this problem: 
"No steps file found" in the settings.json file 

**Expected behavior**
The "No steps file found" issue isn't occured

**Screenshots**
https://www.screencast.com/t/gvhUPRtY

**Cucumberautocomplete part of VSCode settings:**
```
{
    "cucumberautocomplete.steps": [
        "**/*.steps.ts",
        "node_modules/qa-lib/src/step_definitions/*.js"
    ],
    "cucumberautocomplete.syncfeatures": "**/*.feature",
    "cucumberautocomplete.strictGherkinCompletion": true,
    "cucumberautocomplete.smartSnippets": true,
    "cucumberautocomplete.stepsInvariants": true,
    "cucumberautocomplete.customParameters": [
        {
            "parameter":"{ab}",
            "value":"(a|b)"
        },
        // {
        //     "parameter": /\{a.*\}/,
        //     "value":"a"
        // },
    ],
```

Also I get this error after trying lunch test:
```
> ng e2e
Your global Angular CLI version (7.1.4) is greater than your local
version (6.2.5). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
[15:52:27] I/file_manager - creating folder D:\Automation\New folder\node_modules\protractor\node_modules\webdriver-manager\selenium
[15:52:27] I/config_source - curl -oD:\Automation\New folder\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[15:52:28] I/downloader - curl -oD:\Automation\New folder\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_2.45.zip https://chromedriver.storage.googleapis.com/2.45/chromedriver_win32.zip
[15:52:29] I/update - chromedriver: unzipping chromedriver_2.45.zip
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:742:20)
    at ChildProcess.target.send (internal/child_process.js:626:19)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (D:\Automation\New folder\node_modules\@angular-devkit\build-angular\src\utils\run-module-as-observable-fork.js:57:23)
    at Observable._trySubscribe (D:\Automation\New folder\node_modules\rxjs\internal\Observable.js:43:25)
    at Observable.subscribe (D:\Automation\New folder\node_modules\rxjs\internal\Observable.js:29:22)
    at D:\Automation\New folder\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (D:\Automation\New folder\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (D:\Automation\New folder\node_modules\rxjs\internal\operators\mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (D:\Automation\New folder\node_modules\rxjs\internal\operators\mergeMap.js:72:14)
    at MergeMapSubscriber._next (D:\Automation\New folder\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:746:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

versions: 
  "dependencies": {
    "@angular/core": "^7.1.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.8.5",
    "@angular/cli": "^6.2.5",
    "@angular/compiler-cli": "^6.1.10",
    "@angular/language-service": "^6.1.10",
    "@types/chai": "^4.1.6",
    "@types/chai-as-promised": "^7.1.0",
    "@types/cucumber": "^4.0.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "codelyzer": "~4.3.0",
    "cucumber": "^5.0.2",
    "cucumber-junit": "^1.7.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "protractor": "^5.4.2",
    "protractor-cucumber-framework": "^6.1.1",
    "puppeteer": "^1.9.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"

**Comment by alexkrechik** [comment]
Hey! Are You sure, that these steps are present (you did `npm install` or `yarn`).
Unfortunately, test launching part is out of extension responsibility.

**Comment by tshroza** [comment]
yes, I did npm install

**Comment by alexkrechik** [comment]
Please comment/reopen issue if valid.

**Comment by tobynz-phl** [comment]
"cucumberautocomplete.steps": [
        "**/*.steps.ts",

should this be steps.js  ?

**Comment by alexkrechik** [comment]
Should be actual valid path you are using. If all the step definitions names are using "**/*.steps.ts" format (ex. `my.steps.ts`) - you should use this mask.
